apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: roxsross12/wanderlust:frontend-v1
        env: 
          # - name: VITE_API_PATH
          #   value: "http://backend:5000" 
          - name: VITE_API_PATH
            value: "http://localhost:5000" 
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173
--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30000
    protocol: TCP