services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
    networks:
      - roxsross-network

  backend:
    container_name: backend
    image: roxsross12/roxs-travelblog:backend-REPLACE
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - roxsross-network
    environment:
      - MONGODB_URI=mongodb://mongo/wanderlust
      - REDIS_URL=redis:6379

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - roxsross-network

networks:
  roxsross-network:
    driver: bridge

volumes:
  data: