name: CI
on:
#dsparar el pipeline de forma manual
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  ci:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - name: primer paso correr script
        run: echo Hello, world!

  cd:
    runs-on: arc-runner-set
    needs: [ci]
    steps:
      - uses: actions/checkout@v4
      - name: primer paso correr script
        run: echo Hello, world!
