name: CI
on:
#dsparar el pipeline de forma manual
  workflow_dispatch:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: primer paso correr script
        run: echo Hello, world!

  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: primer paso correr script
        run: echo Hello, world!
