name: CI
on:
#dsparar el pipeline de forma manual
  workflow_dispatch:
  push:
    branches: [ wanderlust ]
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: '21'
      - name: Install dependencies
        run: | 
          cd frontend
          npm install
      - name: run test
        run: | 
          cd frontend
          npm run test
  ci-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: primer paso correr script
        run: echo Hello, world!
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: '21'
      - name: Install dependencies
        run: | 
          cd backend
          npm install          
      - name: run test
        run: | 
          cd backend
          npm run test
